<?php

namespace ContainerW8KjLxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nej6fSqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nej6fSq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nej6fSq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BaseController::ListCharacter' => ['privates', '.service_locator.fIVG_E.', 'get_ServiceLocator_FIVGE_Service', true],
            'App\\Controller\\BaseController::safeSearch' => ['privates', '.service_locator.fIVG_E.', 'get_ServiceLocator_FIVGE_Service', true],
            'App\\Controller\\BaseController::searchCharacter' => ['privates', '.service_locator.fIVG_E.', 'get_ServiceLocator_FIVGE_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BaseController:ListCharacter' => ['privates', '.service_locator.fIVG_E.', 'get_ServiceLocator_FIVGE_Service', true],
            'App\\Controller\\BaseController:safeSearch' => ['privates', '.service_locator.fIVG_E.', 'get_ServiceLocator_FIVGE_Service', true],
            'App\\Controller\\BaseController:searchCharacter' => ['privates', '.service_locator.fIVG_E.', 'get_ServiceLocator_FIVGE_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BaseController::ListCharacter' => '?',
            'App\\Controller\\BaseController::safeSearch' => '?',
            'App\\Controller\\BaseController::searchCharacter' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BaseController:ListCharacter' => '?',
            'App\\Controller\\BaseController:safeSearch' => '?',
            'App\\Controller\\BaseController:searchCharacter' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
