<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBK1qku9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBK1qku9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBK1qku9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBK1qku9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBK1qku9\App_KernelDevDebugContainer([
    'container.build_hash' => 'BK1qku9',
    'container.build_id' => '7c9bcf20',
    'container.build_time' => 1645026825,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBK1qku9');
